# Maximum amount of blocks that can be selected at once. -1 for no limit.
max_selection_size: 500_000

# Blocks that cannot be pasted, set, filled, replaced, etc.
blocked_blocks:
  - bedrock
  - barrier
  - end_portal_frame
  - command_block
  - repeating_command_block
  - chain_command_block
  - structure_block
  - structure_void
  - spawner

# Blocks that give a notification to the console when used.
notified_blocks:
  - bedrock
  - barrier
  - end_portal_frame
  - command_block
  - repeating_command_block
  - chain_command_block
  - structure_block
  - structure_void
  - spawner

# Log notifications to a file.
log_notifications: false

# Effect of selection - Default: HAPPY_VILLAGER.
select_effect: HAPPY_VILLAGER

# Effect of constant outline - Default: HAPPY_VILLAGER.
outline_effect: HAPPY_VILLAGER

# Play sound when a selection is made.
play_sound: false

# Sound of selection - Default: BLOCK_NOTE_BLOCK_PLING.
select_sound: BLOCK_NOTE_BLOCK_PLING

# Complete effect list: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
# Complete sound list: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html