name: Terranite
version: '1.2.0'
main: jinzo.terranite.Terranite
api-version: '1.21'
commands:
  s:
    description: Base command for Terranite
    aliases: [terra, terranite, selection]
    permission: terranite.use
    permission-message: You do not have permission to use this command.
permissions:
  terranite.use:
    description: Allows use of the Terranite base command and its aliases
    default: op
  terranite.admin:
    description: Allows use of administrative commands for Terranite
    default: op
  terranite.exempt.*:
    description: Allows players to bypass all restrictions for Terranite commands
    default: op
  terranite.exempt.selection:
    description: Allows players to bypass selection requirements for Terranite commands
    default: op
  terranite.exempt.blockedBlocks:
    description: Allows players to bypass block requirements for Terranite commands
    default: op
  terranite.exempt.notifiedBlocks:
    description: Allows players to bypass notification requirements for Terranite commands
    default: op
