name: Terranite
version: '1.1.0'
main: jinzo.terranite.Terranite
api-version: '1.21'
commands:
  s:
    description: Base command for Terranite
    aliases: [terra, terranite, selection]
    permission: terranite.use
    permission-message: You do not have permission to use this command.
permissions:
  terranite.use:
    description: Allows use of the Terranite base command and its aliases
    default: op
  terranite.admin:
    description: Allows use of administrative commands for Terranite
    default: op
